# Generated by Django 4.1.3 on 2022-11-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleint',
            fields=[
                ('Client_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Client_Name', models.CharField(max_length=500)),
                ('Project_Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_Name', models.CharField(max_length=500)),
                ('Cleint_Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=500)),
                ('Gmail', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('Project_Name', models.CharField(max_length=500)),
            ],
        ),
    ]
